name: Build

on:
  push:
    branches: [ main, actions ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-22.04]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
  
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: choco install ninja

    - name: Configure MSVC build environment (Windows)
      uses: ilammy/msvc-dev-cmd@v1.13.0
      if: runner.os == 'Windows'

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y cmake clang libc++-14-dev libc++abi-14-dev ninja-build

    - name: Run native/build-native.py
      run: python native/build-native.py

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.os }}
        path: |
          native/out

  package:
    needs: build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.x'

    - name: Download build artifacts (windows-latest)
      uses: actions/download-artifact@v4
      with:
        name: build-windows-latest
        path: native/out

    - name: Download build artifacts (ubuntu-22.04)
      uses: actions/download-artifact@v4
      with:
        name: build-ubuntu-22.04
        path: native/out

    - name: Build NuGet package
      run: dotnet build managed/GLTF2Image/GLTF2Image.csproj

    - name: Upload NuGet package
      uses: actions/upload-artifact@v4
      with:
        name: nuget-package
        path: managed/GLTF2Image/bin/Release/*.nupkg
